# Generated by Django 4.0.5 on 2022-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
